#!/usr/bin/python

# script to export pvd files (generated by FEniCS solution) to csv (plottable)

from paraview.simple import *
import sys

for i_field_idx in [1]:#range(1,4):
    
    print 'Starting field ' + str(i_field_idx) + '... ',
    sys.stdout.flush()

    fieldname = 'u_' + str(i_field_idx)
    i_infilename = 'reaction_system/' + fieldname +'.pvd'
    i_field = PVDReader(FileName=i_infilename)
    
    i_outfilename = 'reaction_system/' + fieldname +'.csv'
    SaveData(i_outfilename, proxy=i_field, UseScientificNotation=1, WriteAllTimeSteps=1)

    print 'Done.'
